### ISSUE TITLE
not working for windows

### ISSUE THREAD

**Issue by BeanWei** [aklinker1/wxt#48]
wxt is a very coooool framework, thanks for your work.

Is it ready for production now? I run the templates(vue) on windows, but it NOT woking.

```
> wxt prepare


WXT 0.2.4                                                                                                     08:54:00
ℹ Generating types...                                                                                        08:54:00

 ERROR  defineBackground is not defined
```

**Comment by aklinker1** [comment]
I have not done any testing on Windows, but it works on Mac/Linux.

I'm using it in production on one of my extensions: https://github.com/aklinker1/github-better-line-counts

There are a few high priority issues that need fixed (#37, #38, #39), I wouldn't recommend using it yet.

I'm gonna work on those this weekend. I'll also work on adding windows support.

That said, if you end up trying it out and have feedback, I'd love to hear it!

**Comment by aklinker1** [comment]
@BeanWei There were some issues with the templates causing the "defineBackground is not defined" error, but they should be working now. I've also added some validation in CI so they don't break again.

See [`v0.2.5`](https://github.com/aklinker1/wxt/releases/tag/v0.2.5)

Gonna be working on adding Windows support later today.

**Comment by aklinker1** [comment]
@BeanWei [`v0.3.0`](https://github.com/aklinker1/wxt/releases/tag/v0.3.0) adds support for Windows. Let me know if you run into any errors.

I'm updating the template projects to v0.3 right now

**Comment by BeanWei** [comment]
@aklinker1 good job, man! Now it is working on Windows.

BTW: I add the solid template, see this pr https://github.com/aklinker1/wxt/pull/63

Now i can enjoy WXT!!!

Thx again!

**Comment by aklinker1** [comment]
Awesome, thank you! Let me know if you run into any issues. Glad to see WXT's first contribution :)
